---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mychart.fullname" . }}
  labels:
    {{- include "mychart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mychart.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mychart.labels" . | nindent 8 }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "mychart.serviceAccountName" . }}
      {{- end }}
      volumes:
      - name: {{ include "mychart.fullname" . }}
        configMap:
          name: {{ include "mychart.fullname" . }}
          items:
          - key: {{ .Values.configMap.item.key }}
            path: {{ .Values.configMap.item.path }}
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: {{ include "mychart.fullname" . }}
            mountPath: {{ .Values.volumeMount.mountPath }}
